var parsedUrl = new URL(window.location.href);

// Assignment 3: Query the database to retrieve ALL of its contents.
// Called in: query.html 
// If Successful: Display all entries in a database   
function query() {
    // Extract the JWT token from the cookie which is generated by checkTOTP()  and stored in browser
    const JWT = document.cookie
        .split("; ")
        .find((row) => row.startsWith("JWT="))?.split("=")[1];
    console.log("JWT:",JWT);
    if (!JWT) {
        alert("JWT token is missing! Please log in again.");
        return;
    }

    fetch("http://" + parsedUrl.host + "/query", {
        method: "GET",
        headers: {
            "Authorization": JWT, 
        },
    })
    .then((resp) => resp.text()) // the API Route will only return text 
    .then((data) => {
        document.getElementById("response").innerHTML = data;
    })
    .catch((err) => {
        console.log(err);
        alert("An error occurred while querying the database.");
    });
}


// added for roles assignment
function query2() {
    // Extract the JWT token from the cookie which is generated by checkTOTP()  and stored in browser
    const JWT = document.cookie
        .split("; ")
        .find((row) => row.startsWith("JWT="))?.split("=")[1];
    console.log("JWT:",JWT);
    if (!JWT) {
        alert("JWT token is missing! Please log in again.");
        return;
    }

    fetch("http://" + parsedUrl.host + "/query2", {
        method: "GET",
        headers: {
            "Authorization": JWT, 
        },
    })
    .then((resp) => resp.text()) // the API Route will only return text 
    .then((data) => {
        document.getElementById("response").innerHTML = data;
    })
    .catch((err) => {
        console.log(err);
        alert("An error occurred while querying the database.");
    });
}


// Assignment 1: Login using username and password, check if both are in the database. If successfull, go to totp.html
// Called in: index.html
// If Successful: Go to totp.html
function login() {
    const username = document.getElementById("username").value;
    const password = document.getElementById("password").value;

    // Validate that both fields are filled
    if (!username || !password) {
        alert("Please fill in both the username and password fields.");
        return; // Stop execution if either field is empty
    }

    let body = JSON.stringify({
        username: username,
        password: password
    });

    fetch("http://localhost:3000/login", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: body
    })
    .then((resp) => {
        if (resp.status === 200) {
            return resp.text().then(() => {
                // Generate a cookie with just the username
                document.cookie = "username=" + username;
                console.log("Cookie set:", document.cookie); // Debugging
                location.href = "http://localhost/totp.html";
            });
        } else if (resp.status === 401) {
            alert("Username or Password is incorrect");
        } else {
            alert("Server Error");
        }
    })
    .catch((err) => {
        console.log("Error during login:", err);
    });
}


function initializeLoginPage() {
    const form = document.getElementById("login-form");

    // Handle form submission
    form.addEventListener("submit", function (event) {
        event.preventDefault();
        login();
    });

    // Trigger login on Enter key press
    document.addEventListener("keydown", function (event) {
        if (event.key === "Enter") {
            event.preventDefault();
            login();
        }
    });
}

// Initialize event listeners when the DOM content is fully loaded
document.addEventListener("DOMContentLoaded", function () {
    if (document.getElementById("login-form")) {
        initializeLoginPage();
    }
});


// Assignment 2: Generate a TOTP on the server side automatically, and a user side manually. Compare the two TOTP's 
// Called in: totp.html
// If Successful: Go to query.html
function checkTOTP() {
    const username = document.cookie
        .split("; ")
        .find((row) => row.startsWith("username="))?.split("=")[1];

    console.log("Retrieved username from cookie:", username);

    if (!username) {
        alert("Username is missing! Please log in again.");
        return;
    }

    let stringifiedBody = JSON.stringify({
        totp: document.getElementById("totpCode").value,
        username: username
    });

    fetch("http://" + parsedUrl.host + ":3000/checkTOTP", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: stringifiedBody
    })
    .then((resp) => {
        if (resp.status === 200) {
            return resp.text().then((token) => {
                document.cookie = `JWT=${token}`; // Removed Secure and HttpOnly for local testing                console.log("JWT Cookie set:", document.cookie); // Debugging
                location.href = "http://" + parsedUrl.host + "/query.html";
            });
        } else if (resp.status === 401) {
            alert("TOTP Code Incorrect");
        } else {
            alert("Server Error");
        }
    })
    .catch((err) => {
        console.log(err);
    });
}

