version: '3'
services:
  mysql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-users:/docker-entrypoint-initdb.d/
  server-user:
    build: ./server-user
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-user
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=ef79
      - TOTPSECRET=supersecretcode
      - JWTSECRET=othersupersecretcode
    volumes:
      - ./server/backend-users:/app/backend
    ports:
      - "8001:80"
  mysql-data:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-data:/docker-entrypoint-initdb.d/
  server-data:
    build: ./server-data
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-data
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server/backend-data:/app/backend
      - ./server/frontend:/app/frontend
    ports:
      - "80:80"
